[build]
builder = "nixpacks"
buildCommand = "cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm run prisma:migrate:deploy && npm start"
healthcheckPath = "/api/v1/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
